import { CollectionOptions } from '@nocobase/database';
export default {
  name: 'msGraphGatewayAuditLogs',
  fields: [
    { name: 'requestId', type: 'string', index: true },
    { name: 'jobId', type: 'string', index: true },
    { name: 'operation', type: 'string' },
    { name: 'status', type: 'string' },
    { name: 'httpStatus', type: 'integer' },
    { name: 'graphHttpStatus', type: 'integer' },
    { name: 'graphRequestId', type: 'string' },
    { name: 'route', type: 'string' },
    { name: 'method', type: 'string' },
    { name: 'apiKeyId', type: 'string' },
    { name: 'apiKeyPrefix', type: 'string' },
    { name: 'clientIp', type: 'string' },
    { name: 'userAgent', type: 'text' },
    { name: 'requestSize', type: 'integer' },
    { name: 'requestFields', type: 'json' },
    { name: 'errorCode', type: 'string' },
    { name: 'errorName', type: 'string' },
    { name: 'startedAt', type: 'datetime' },
    { name: 'finishedAt', type: 'datetime' },
    { name: 'details', type: 'json' },
    { name: 'durationMs', type: 'integer' },
    { name: 'attempt', type: 'integer' },
    { name: 'error', type: 'text' },
  ],
} as CollectionOptions;
