import AdmZip from 'adm-zip';

import { isRecord, type RegistrySkillCandidateV1, type RegistrySkillManifestV1 } from '../contracts/types';
import { RegistryError } from '../contracts/errors';
import { canonicalJson, sha256 } from './canonical-json';
import { normalizeRelativePath } from './validation';

export function parseArtifactLimit(
  value: string | undefined,
  fallback: number,
  maximum = Number.MAX_SAFE_INTEGER,
): number {
  const normalized = value?.trim();
  if (!normalized || !/^[1-9]\d*$/.test(normalized)) {
    return fallback;
  }
  const parsed = Number(normalized);
  return Number.isSafeInteger(parsed) && parsed <= maximum ? parsed : fallback;
}

const MAX_FILES = parseArtifactLimit(process.env.SKILL_REGISTRY_MAX_FILES, 2000, 10_000);
const MAX_EXPANDED_BYTES = parseArtifactLimit(
  process.env.SKILL_REGISTRY_MAX_EXPANDED_BYTES,
  250 * 1024 * 1024,
  1024 * 1024 * 1024,
);
const MAX_ARTIFACT_BYTES = parseArtifactLimit(
  process.env.SKILL_REGISTRY_MAX_ARTIFACT_BYTES,
  50 * 1024 * 1024,
  256 * 1024 * 1024,
);
const MAX_MANIFEST_BYTES = parseArtifactLimit(
  process.env.SKILL_REGISTRY_MAX_MANIFEST_BYTES,
  10 * 1024 * 1024,
  25 * 1024 * 1024,
);
const MAX_INSTRUCTION_BYTES = parseArtifactLimit(
  process.env.SKILL_REGISTRY_MAX_INSTRUCTION_BYTES,
  10 * 1024 * 1024,
  25 * 1024 * 1024,
);
export const ARTIFACT_LIMITS = Object.freeze({
  maxFiles: MAX_FILES,
  maxExpandedBytes: MAX_EXPANDED_BYTES,
  maxArtifactBytes: MAX_ARTIFACT_BYTES,
  maxManifestBytes: MAX_MANIFEST_BYTES,
  maxInstructionBytes: MAX_INSTRUCTION_BYTES,
});
const DETERMINISTIC_ZIP_TIME = new Date('1980-01-01T00:00:00.000Z');
const MANIFEST_PATH = 'manifest.json';
const MANIFEST_PATH_KEY = MANIFEST_PATH.toLowerCase();
const INSTRUCTION_PATH_KEY = 'skill.md';

export interface BuiltArtifact {
  content: Buffer;
  digest: string;
  manifestDigest: string;
  expandedSizeBytes: number;
}

function pathCollisionKey(path: string): string {
  return path.normalize('NFC').toLowerCase();
}

function validateManifest(manifest: unknown): asserts manifest is RegistrySkillManifestV1 {
  if (!isRecord(manifest)) {
    throw new RegistryError('INVALID_MANIFEST', 422, 'Artifact manifest.json must be an object.');
  }
  if (manifest.schemaVersion !== 'registry.skill.nocobase.io/v1') {
    throw new RegistryError('INVALID_MANIFEST', 422, 'Unsupported skill manifest schemaVersion.');
  }
  if (
    typeof manifest.name !== 'string' ||
    !manifest.name.trim() ||
    typeof manifest.displayName !== 'string' ||
    !manifest.displayName.trim() ||
    !isRecord(manifest.runtime) ||
    typeof manifest.runtime.entrypoint !== 'string' ||
    !manifest.runtime.entrypoint.trim()
  ) {
    throw new RegistryError('INVALID_MANIFEST', 422, 'Manifest requires displayName and runtime.entrypoint.');
  }
  if (typeof manifest.runtime.kind !== 'string' || !['python', 'node', 'instruction'].includes(manifest.runtime.kind)) {
    throw new RegistryError('INVALID_MANIFEST', 422, 'Manifest runtime.kind must be python, node, or instruction.');
  }
}

export function buildArtifact(candidate: RegistrySkillCandidateV1): BuiltArtifact {
  validateManifest(candidate.manifest);
  const maximumCandidateFiles = Math.max(0, MAX_FILES - 1);
  if (candidate.files.length === 0 || candidate.files.length > maximumCandidateFiles) {
    throw new RegistryError(
      'ARTIFACT_TOO_LARGE',
      422,
      `Artifact must contain between 1 and ${maximumCandidateFiles} candidate files; manifest.json counts toward the ${MAX_FILES}-file limit.`,
    );
  }

  const manifestJson = canonicalJson(candidate.manifest);
  const manifestData = Buffer.from(manifestJson, 'utf8');
  if (manifestData.length > MAX_MANIFEST_BYTES) {
    throw new RegistryError('ARTIFACT_TOO_LARGE', 422, 'Artifact manifest.json exceeds the configured limit.');
  }
  const entrypoint = normalizeRelativePath(candidate.manifest.runtime.entrypoint);
  const files = [...candidate.files]
    .map((file) => {
      if (!Buffer.isBuffer(file.content)) {
        throw new RegistryError('INVALID_MANIFEST', 422, `Artifact file ${file.path} does not contain binary data.`);
      }
      return { path: normalizeRelativePath(file.path), content: file.content };
    })
    .sort((left, right) => left.path.localeCompare(right.path));
  const filePaths = new Set<string>();
  const collisionKeys = new Set<string>();
  let expandedSizeBytes = manifestData.length;

  if (expandedSizeBytes > MAX_EXPANDED_BYTES) {
    throw new RegistryError('ARTIFACT_TOO_LARGE', 422, 'Artifact expanded size exceeds the configured limit.');
  }

  for (const file of files) {
    const collisionKey = pathCollisionKey(file.path);
    if (collisionKey === MANIFEST_PATH_KEY) {
      throw new RegistryError(
        'ARTIFACT_UNSAFE_PATH',
        422,
        `${MANIFEST_PATH} is generated by the registry and cannot be supplied by a candidate.`,
      );
    }
    if (collisionKeys.has(collisionKey)) {
      throw new RegistryError(
        'ARTIFACT_UNSAFE_PATH',
        422,
        `Artifact has a case-insensitive or Unicode-normalized path collision at ${file.path}.`,
      );
    }
    filePaths.add(file.path);
    collisionKeys.add(collisionKey);
    if (collisionKey === INSTRUCTION_PATH_KEY && file.content.length > MAX_INSTRUCTION_BYTES) {
      throw new RegistryError('ARTIFACT_TOO_LARGE', 422, 'Artifact SKILL.md exceeds the configured limit.');
    }
    expandedSizeBytes += file.content.length;
    if (expandedSizeBytes > MAX_EXPANDED_BYTES) {
      throw new RegistryError('ARTIFACT_TOO_LARGE', 422, 'Artifact expanded size exceeds the configured limit.');
    }
  }

  if (!filePaths.has(entrypoint)) {
    throw new RegistryError('INVALID_MANIFEST', 422, `Entrypoint ${entrypoint} is not included in the artifact.`);
  }

  const archive = new AdmZip();
  const manifestEntry = archive.addFile(MANIFEST_PATH, manifestData, '', 0o644);
  manifestEntry.header.time = DETERMINISTIC_ZIP_TIME;
  for (const file of files) {
    const entry = archive.addFile(file.path, file.content, '', 0o644);
    entry.header.time = DETERMINISTIC_ZIP_TIME;
  }
  const content = archive.toBuffer();
  if (content.length > MAX_ARTIFACT_BYTES) {
    throw new RegistryError('ARTIFACT_TOO_LARGE', 422, 'Artifact compressed size exceeds the configured limit.');
  }
  return {
    content,
    digest: sha256(content),
    manifestDigest: sha256(manifestJson),
    expandedSizeBytes,
  };
}

export function unpackArtifact(content: Buffer): { manifest: RegistrySkillManifestV1; files: Map<string, Buffer> } {
  if (content.length > MAX_ARTIFACT_BYTES) {
    throw new RegistryError('ARTIFACT_TOO_LARGE', 422, 'Artifact compressed size exceeds the configured limit.');
  }
  const archive = new AdmZip(content);
  const files = new Map<string, Buffer>();
  const collisionKeys = new Set<string>();
  let expandedSizeBytes = 0;
  for (const entry of archive.getEntries()) {
    const entryName = entry.entryName.replace(/\\/g, '/');
    const path = normalizeRelativePath(
      entry.isDirectory && entryName.endsWith('/') ? entryName.slice(0, -1) : entryName,
    );
    const collisionKey = pathCollisionKey(path);
    if (collisionKeys.has(collisionKey)) {
      throw new RegistryError(
        'ARTIFACT_UNSAFE_PATH',
        422,
        `Artifact has a case-insensitive or Unicode-normalized path collision at ${path}.`,
      );
    }
    if (collisionKey === MANIFEST_PATH_KEY && path !== MANIFEST_PATH) {
      throw new RegistryError(
        'ARTIFACT_UNSAFE_PATH',
        422,
        `Artifact manifest must use the exact path ${MANIFEST_PATH}.`,
      );
    }
    collisionKeys.add(collisionKey);
    if (entry.isDirectory) {
      continue;
    }
    if (files.size >= MAX_FILES) {
      throw new RegistryError('ARTIFACT_TOO_LARGE', 422, 'Artifact exceeds extraction limits.');
    }
    // Reject on the declared size BEFORE decompressing, or a zip bomb entry would be
    // fully expanded into memory just to find out it is too large.
    const entryLimit = collisionKey === MANIFEST_PATH_KEY ? MAX_MANIFEST_BYTES : MAX_EXPANDED_BYTES;
    if (
      !Number.isSafeInteger(entry.header.size) ||
      entry.header.size < 0 ||
      entry.header.size > entryLimit ||
      (collisionKey === INSTRUCTION_PATH_KEY && entry.header.size > MAX_INSTRUCTION_BYTES) ||
      expandedSizeBytes + entry.header.size > MAX_EXPANDED_BYTES
    ) {
      throw new RegistryError('ARTIFACT_TOO_LARGE', 422, 'Artifact exceeds extraction limits.');
    }
    const data = entry.getData();
    // Declared sizes can lie; re-check with the actual decompressed bytes.
    expandedSizeBytes += data.length;
    if (
      data.length > entryLimit ||
      (collisionKey === INSTRUCTION_PATH_KEY && data.length > MAX_INSTRUCTION_BYTES) ||
      expandedSizeBytes > MAX_EXPANDED_BYTES
    ) {
      throw new RegistryError('ARTIFACT_TOO_LARGE', 422, 'Artifact exceeds extraction limits.');
    }
    files.set(path, data);
  }
  const manifestData = files.get(MANIFEST_PATH);
  if (!manifestData) {
    throw new RegistryError('INVALID_MANIFEST', 422, `Artifact does not contain ${MANIFEST_PATH}.`);
  }
  let manifest: unknown;
  try {
    manifest = JSON.parse(manifestData.toString('utf8'));
  } catch {
    throw new RegistryError('INVALID_MANIFEST', 422, 'Artifact manifest.json is not valid JSON.');
  }
  validateManifest(manifest);
  const entrypoint = normalizeRelativePath(manifest.runtime.entrypoint);
  if (!files.has(entrypoint)) {
    throw new RegistryError('INVALID_MANIFEST', 422, 'Artifact entrypoint is missing.');
  }
  return { manifest, files };
}
