import { defineCollection } from '@nocobase/database';

export default defineCollection({
  name: 'agentLoopPatterns',
  title: 'Agent Loop Patterns',
  fields: [
    { name: 'id', type: 'bigInt', autoIncrement: true, primaryKey: true },
    { name: 'key', type: 'string', length: 120, allowNull: false, unique: true },
    { name: 'title', type: 'string', length: 240, allowNull: false },
    { name: 'description', type: 'text' },
    { name: 'goalTemplate', type: 'text', allowNull: false },
    { name: 'enabled', type: 'boolean', defaultValue: false },
    { name: 'autonomyLevel', type: 'string', length: 10, defaultValue: 'L1' },
    { name: 'triggerType', type: 'string', length: 20, defaultValue: 'manual' },
    { name: 'cronExpression', type: 'string', length: 120 },
    { name: 'timezone', type: 'string', length: 80 },
    { name: 'eventKey', type: 'string', length: 160 },
    { name: 'triggerConfig', type: 'json', defaultValue: {} },
    { name: 'leaderUsername', type: 'string', length: 100, allowNull: false },
    { name: 'makerUsernames', type: 'json', defaultValue: [] },
    { name: 'verifierUsername', type: 'string', length: 100, allowNull: false },
    { name: 'leaderHarnessTag', type: 'string', length: 100, defaultValue: 'default' },
    { name: 'makerHarnessTag', type: 'string', length: 100, defaultValue: 'default' },
    { name: 'verifierHarnessTag', type: 'string', length: 100, defaultValue: 'safe' },
    { name: 'repositoryKey', type: 'string', length: 200 },
    { name: 'repositoryRoot', type: 'string', length: 1000 },
    { name: 'baseRef', type: 'string', length: 200, defaultValue: 'main' },
    { name: 'actingOn', type: 'json', defaultValue: [] },
    { name: 'policy', type: 'json', defaultValue: {} },
    { name: 'createdBy', type: 'belongsTo', target: 'users', foreignKey: 'createdById' },
    { name: 'updatedBy', type: 'belongsTo', target: 'users', foreignKey: 'updatedById' },
    { name: 'createdAt', type: 'date' },
    { name: 'updatedAt', type: 'date' },
  ],
  indexes: [
    { unique: true, fields: ['key'] },
    { fields: ['enabled', 'triggerType'] },
    { fields: ['leaderUsername'] },
    { fields: ['verifierUsername'] },
    { fields: ['repositoryKey'] },
  ],
});
