import { getVisualizationTemplateRegistry, defaultVisualizationRoles, VisualizationTemplate } from '../registry';

export const jobManagementVisualizationTemplates: VisualizationTemplate[] = [
  {
    key: 'job-management.overview',
    title: 'Job management overview',
    description: 'Core status, owner, and creation trend charts for job and task collections.',
    group: 'Work management',
    roles: defaultVisualizationRoles,
    charts: [
      {
        key: 'total-jobs',
        title: 'Total jobs',
        chartType: 'antd.statistic',
        measures: [{ role: 'record', aggregation: 'count', alias: 'value' }],
        config: { field: 'value', title: 'Total jobs' },
      },
      {
        key: 'jobs-by-status',
        title: 'Jobs by status',
        chartType: 'ant-design-charts.pie',
        measures: [{ role: 'record', aggregation: 'count', alias: 'value' }],
        dimensions: [{ role: 'status' }],
        config: { angleField: 'value', colorField: 'status' },
      },
      {
        key: 'jobs-by-assignee',
        title: 'Jobs by assignee',
        chartType: 'ant-design-charts.bar',
        measures: [{ role: 'record', aggregation: 'count', alias: 'value' }],
        dimensions: [{ role: 'assignee' }],
        config: { xField: 'assignee', yField: 'value' },
      },
      {
        key: 'jobs-created-trend',
        title: 'Jobs created trend',
        chartType: 'ant-design-charts.line',
        measures: [{ role: 'record', aggregation: 'count', alias: 'value' }],
        dimensions: [{ role: 'createdAt', format: 'YYYY-MM-DD', alias: 'createdAt' }],
        config: { xField: 'createdAt', yField: 'value', smooth: true },
      },
    ],
  },
  {
    key: 'job-management.status-priority',
    title: 'Status and priority monitor',
    description: 'Status and priority distribution for operational job tracking.',
    group: 'Work management',
    roles: defaultVisualizationRoles,
    charts: [
      {
        key: 'status-breakdown',
        title: 'Status breakdown',
        chartType: 'ant-design-charts.column',
        measures: [{ role: 'record', aggregation: 'count', alias: 'value' }],
        dimensions: [{ role: 'status' }],
        config: { xField: 'status', yField: 'value' },
      },
      {
        key: 'priority-breakdown',
        title: 'Priority breakdown',
        chartType: 'ant-design-charts.pie',
        measures: [{ role: 'record', aggregation: 'count', alias: 'value' }],
        dimensions: [{ role: 'priority' }],
        config: { angleField: 'value', colorField: 'priority' },
      },
      {
        key: 'status-by-priority',
        title: 'Status by priority',
        chartType: 'ant-design-charts.column',
        measures: [{ role: 'record', aggregation: 'count', alias: 'value' }],
        dimensions: [{ role: 'status' }, { role: 'priority' }],
        config: { xField: 'status', yField: 'value', seriesField: 'priority', isStack: true },
      },
    ],
  },
  {
    key: 'job-management.throughput',
    title: 'Throughput monitor',
    description: 'Created, completed, and due date trends for delivery monitoring.',
    group: 'Work management',
    roles: defaultVisualizationRoles,
    charts: [
      {
        key: 'created-throughput',
        title: 'Created throughput',
        chartType: 'ant-design-charts.line',
        measures: [{ role: 'record', aggregation: 'count', alias: 'value' }],
        dimensions: [{ role: 'createdAt', format: 'YYYY-MM-DD', alias: 'createdAt' }],
        config: { xField: 'createdAt', yField: 'value', smooth: true },
      },
      {
        key: 'completed-throughput',
        title: 'Completed throughput',
        chartType: 'ant-design-charts.line',
        measures: [{ role: 'record', aggregation: 'count', alias: 'value' }],
        dimensions: [{ role: 'completedAt', format: 'YYYY-MM-DD', alias: 'completedAt' }],
        config: { xField: 'completedAt', yField: 'value', smooth: true },
      },
      {
        key: 'due-date-load',
        title: 'Due date load',
        chartType: 'ant-design-charts.column',
        measures: [{ role: 'record', aggregation: 'count', alias: 'value' }],
        dimensions: [{ role: 'dueDate', format: 'YYYY-MM-DD', alias: 'dueDate' }],
        config: { xField: 'dueDate', yField: 'value' },
      },
    ],
  },
];

export const workDashboardVisualizationTemplates: VisualizationTemplate[] = [
  {
    key: 'work.overview',
    title: 'Work overview',
    description: 'Core health dashboard for job, task, and ticket collections.',
    group: 'Work management',
    roles: defaultVisualizationRoles,
    charts: [
      {
        key: 'total-work-items',
        title: 'Total work items',
        chartType: 'antd.statistic',
        measures: [{ role: 'record', aggregation: 'count', alias: 'value' }],
        config: { field: 'value', title: 'Total work items' },
      },
      {
        key: 'work-by-status',
        title: 'Work by status',
        chartType: 'ant-design-charts.pie',
        measures: [{ role: 'record', aggregation: 'count', alias: 'value' }],
        dimensions: [{ role: 'status' }],
        config: { angleField: 'value', colorField: 'status' },
      },
      {
        key: 'work-by-assignee',
        title: 'Work by assignee',
        chartType: 'ant-design-charts.bar',
        measures: [{ role: 'record', aggregation: 'count', alias: 'value' }],
        dimensions: [{ role: 'assignee' }],
        config: { xField: 'assignee', yField: 'value' },
      },
      {
        key: 'work-created-trend',
        title: 'Created trend',
        chartType: 'ant-design-charts.line',
        measures: [{ role: 'record', aggregation: 'count', alias: 'value' }],
        dimensions: [{ role: 'createdAt', format: 'YYYY-MM-DD', alias: 'createdAt' }],
        config: { xField: 'createdAt', yField: 'value', smooth: true },
      },
    ],
  },
  {
    key: 'work.status-monitor',
    title: 'Status monitor',
    description: 'Status, priority, and ownership distribution for operational tracking.',
    group: 'Work management',
    roles: defaultVisualizationRoles,
    charts: [
      {
        key: 'status-breakdown',
        title: 'Status breakdown',
        chartType: 'ant-design-charts.column',
        measures: [{ role: 'record', aggregation: 'count', alias: 'value' }],
        dimensions: [{ role: 'status' }],
        config: { xField: 'status', yField: 'value' },
      },
      {
        key: 'priority-breakdown',
        title: 'Priority breakdown',
        chartType: 'ant-design-charts.pie',
        measures: [{ role: 'record', aggregation: 'count', alias: 'value' }],
        dimensions: [{ role: 'priority' }],
        config: { angleField: 'value', colorField: 'priority' },
      },
      {
        key: 'status-by-priority',
        title: 'Status by priority',
        chartType: 'ant-design-charts.column',
        measures: [{ role: 'record', aggregation: 'count', alias: 'value' }],
        dimensions: [{ role: 'status' }, { role: 'priority' }],
        config: { xField: 'status', yField: 'value', seriesField: 'priority', isStack: true },
      },
      {
        key: 'assignee-by-status',
        title: 'Assignee by status',
        chartType: 'ant-design-charts.bar',
        measures: [{ role: 'record', aggregation: 'count', alias: 'value' }],
        dimensions: [{ role: 'assignee' }, { role: 'status' }],
        config: { xField: 'assignee', yField: 'value', seriesField: 'status', isStack: true },
      },
    ],
  },
  {
    key: 'work.throughput',
    title: 'Throughput monitor',
    description: 'Created and completed work trends for delivery monitoring.',
    group: 'Work management',
    roles: defaultVisualizationRoles,
    charts: [
      {
        key: 'created-throughput',
        title: 'Created throughput',
        chartType: 'ant-design-charts.line',
        measures: [{ role: 'record', aggregation: 'count', alias: 'value' }],
        dimensions: [{ role: 'createdAt', format: 'YYYY-MM-DD', alias: 'createdAt' }],
        config: { xField: 'createdAt', yField: 'value', smooth: true },
      },
      {
        key: 'completed-throughput',
        title: 'Completed throughput',
        chartType: 'ant-design-charts.line',
        measures: [{ role: 'record', aggregation: 'count', alias: 'value' }],
        dimensions: [{ role: 'completedAt', format: 'YYYY-MM-DD', alias: 'completedAt' }],
        config: { xField: 'completedAt', yField: 'value', smooth: true },
      },
      {
        key: 'due-date-load',
        title: 'Due date load',
        chartType: 'ant-design-charts.column',
        measures: [{ role: 'record', aggregation: 'count', alias: 'value' }],
        dimensions: [{ role: 'dueDate', format: 'YYYY-MM-DD', alias: 'dueDate' }],
        config: { xField: 'dueDate', yField: 'value' },
      },
    ],
  },
];

const registry = getVisualizationTemplateRegistry();
registry.registerMany(jobManagementVisualizationTemplates);
registry.registerMany(workDashboardVisualizationTemplates);
