import { CollectionOptions } from '@nocobase/database';

export default {
  name: 'doc_understanding_config',
  title: 'Document Understanding Config',
  // Model name can be explicitly generated by NocoBase, but we define collection fields.
  fields: [
    { type: 'string', name: 'baseUrl', length: 500 },
    { type: 'string', name: 'authType', length: 20 }, // 'api_key' | 'bearer' | 'custom_header' | 'none'
    { type: 'string', name: 'authKey', length: 500 },
    { type: 'string', name: 'authHeaderName', length: 100 },
    { type: 'integer', name: 'defaultTimeout', defaultValue: 30000 },
    { type: 'integer', name: 'defaultRetries', defaultValue: 2 },
    { type: 'integer', name: 'pollInterval', defaultValue: 5000 },
    { type: 'integer', name: 'pollTimeout', defaultValue: 300000 },
    { type: 'string', name: 'webhookSecret', length: 500 },
  ],
} as CollectionOptions;
