import { defineCollection } from '@nocobase/database';

export default defineCollection({
  name: 'appObservabilityBuckets',
  dataCategory: 'runtime',
  indexes: [
    { fields: ['bucketStart'] },
    { fields: ['appName', 'bucketStart'] },
    { fields: ['nodeId', 'bucketStart'] },
    { fields: ['service', 'operation', 'bucketStart'] },
  ],
  fields: [
    { name: 'bucketStart', type: 'date' },
    { name: 'bucketSeconds', type: 'integer' },
    { name: 'appName', type: 'string' },
    { name: 'nodeId', type: 'string' },
    { name: 'workerMode', type: 'string' },
    { name: 'service', type: 'string' },
    { name: 'operation', type: 'string' },
    { name: 'streaming', type: 'boolean' },
    { name: 'requestCount', type: 'bigInt', defaultValue: 0 },
    { name: 'successCount', type: 'bigInt', defaultValue: 0 },
    { name: 'failureCount', type: 'bigInt', defaultValue: 0 },
    { name: 'cancelledCount', type: 'bigInt', defaultValue: 0 },
    { name: 'rejectedCount', type: 'bigInt', defaultValue: 0 },
    { name: 'maxInflight', type: 'integer', defaultValue: 0 },
    { name: 'uniqueUserEstimate', type: 'integer', defaultValue: 0 },
    { name: 'latencyCount', type: 'bigInt', defaultValue: 0 },
    { name: 'latencySumMs', type: 'double', defaultValue: 0 },
    { name: 'latencyMaxMs', type: 'double', defaultValue: 0 },
    { name: 'latencyHistogram', type: 'json' },
    { name: 'firstByteHistogram', type: 'json' },
    { name: 'bytesIn', type: 'bigInt', defaultValue: 0 },
    { name: 'bytesOut', type: 'bigInt', defaultValue: 0 },
    { name: 'inputTokens', type: 'bigInt', defaultValue: 0 },
    { name: 'outputTokens', type: 'bigInt', defaultValue: 0 },
    { name: 'runtimeSnapshot', type: 'json' },
  ],
});
