import { defineCollection } from '@nocobase/database';

export default defineCollection({
  name: 'skillRegistryVersions',
  title: 'Skill Registry Versions',
  autoGenId: true,
  createdAt: true,
  updatedAt: true,
  indexes: [
    { name: 'skill_registry_versions_package_version', fields: ['packageId', 'version'], unique: true },
    {
      name: 'skill_registry_versions_source_revision_digest',
      fields: ['sourceItemId', 'sourceRevision', 'candidateDigest'],
      unique: true,
    },
    {
      name: 'skill_registry_versions_package_channel_status',
      fields: ['packageId', 'channel', 'status', 'publishedAt', 'id'],
    },
    { name: 'skill_registry_versions_status_created', fields: ['status', 'createdAt'] },
  ],
  fields: [
    {
      type: 'belongsTo',
      name: 'package',
      target: 'skillRegistryPackages',
      foreignKey: 'packageId',
      onDelete: 'RESTRICT',
      allowNull: false,
    },
    {
      type: 'belongsTo',
      name: 'sourceItem',
      target: 'skillRegistrySourceItems',
      foreignKey: 'sourceItemId',
      onDelete: 'RESTRICT',
      allowNull: true,
    },
    { type: 'string', name: 'version', length: 64, allowNull: false },
    { type: 'string', name: 'channel', length: 20, defaultValue: 'stable' },
    { type: 'string', name: 'status', length: 24, defaultValue: 'discovered' },
    { type: 'string', name: 'sourceRevision', length: 128, allowNull: false },
    { type: 'string', name: 'candidateDigest', length: 71, allowNull: false },
    { type: 'json', name: 'manifest', defaultValue: {} },
    { type: 'string', name: 'manifestDigest', length: 71, allowNull: false },
    { type: 'string', name: 'runtime', length: 20, allowNull: false },
    { type: 'string', name: 'entrypoint', length: 500, allowNull: false },
    { type: 'json', name: 'permissions', defaultValue: {} },
    { type: 'json', name: 'dependencies', defaultValue: [] },
    { type: 'json', name: 'compatibility', defaultValue: {} },
    { type: 'text', name: 'changelog', allowNull: true },
    {
      type: 'belongsTo',
      name: 'artifact',
      target: 'skillRegistryArtifacts',
      foreignKey: 'artifactId',
      onDelete: 'RESTRICT',
      allowNull: false,
    },
    { type: 'string', name: 'artifactDigest', length: 71, allowNull: false },
    { type: 'text', name: 'registrySignature', allowNull: true },
    { type: 'string', name: 'signatureKeyId', length: 120, allowNull: true },
    { type: 'json', name: 'validationReport', allowNull: true },
    { type: 'belongsTo', name: 'publishedBy', target: 'users', foreignKey: 'publishedById' },
    { type: 'date', name: 'publishedAt', allowNull: true },
    { type: 'date', name: 'yankedAt', allowNull: true },
    { type: 'text', name: 'yankReason', allowNull: true },
  ],
});
